### ISSUE TITLE
Feature Request: Case Insensitive matching

### ISSUE THREAD

**Issue by chuckgit123** [MatthiasDrexler/altn8-th#1]
I love this addon (used the original altn8 for years) - thanks alot for it!

One thing I miss, though, is the possibility to do case **in**sensitive pattern matching.

Example: I would like to switch between `SomeThingShould.kt` and `someThing.kt`.

It would be awesome if this would be configurable either globally or per pattern. 😀

**Comment by MatthiasDrexler** [comment]
Hey, thanks for your issue. As some kind of "quick fix", I enabled case-insensitive matching hard-coded for all matching types.

Let me know, if I should make it configurable in any kind. If no one is complaining (for example regarding performance issues), I would keep it like that. 1.0.1 is awaiting approval from JetBrains and should be available for download soon.

**Comment by chuckgit123** [comment]
LOL - yeah, that is what I also did locally 😉. 

I can't judge if making it default would result - for some use-cases - in too many related files, which might be a surprise for some (existing) users. Therefore I was suggesting to make it configurable and stick to the current behaviour as default.

For me personally having case-insensitive matching as default would be completely fine.

**Comment by chuckgit123** [comment]
I installed v1.0.1. So far seems to work pretty well. Thanks alot! 😀

**Comment by MatthiasDrexler** [comment]
I introduced a setting to make case sensitivity configurable. Default is case sensitive matching. You need to check the case-insensitive matching setting now.

I will close this issue, since I assume the problem to be fixed :).
